### ISSUE TITLE
Scrolling cells with keyboard (pressing down arrow) is not scrolling the screen

### ISSUE THREAD

**Issue by polvoazul** [aquirdTurtle/Collapsible_Headings#14] opened 2020-01-15 15:58 UTC
With the extension enabled, if you press down arrow while in "cell mode" jupyter will select the next cell, however the screen will not scroll to garantee that said cell is visible.

Disabling the extension restores the original behaviour.

**Comment by stephenkraemer** [comment] 2020-02-05 16:24
However, scrolling with J/K still works :)

**Comment by chris-tng** [comment] 2020-02-07 17:36
+1 I have the same problem

**Comment by stephenkraemer** [comment] 2020-02-07 18:11
... and I have to partially retract my statement: J/K works, but it will unfold cells.

But nevermind, I am just grateful that this exists at all!!

**Comment by chris-tng** [comment] 2020-02-07 18:29
I actually had to change my habit to using J/K for navigating, thanks for the tip. Hope it will be fixed soon

**Comment by aquirdTurtle** [comment] 2020-02-10 22:38
Thanks everyone for bringing attention to this. With the Jupyterlab 2.0 upgrade coming soon, I'm think I'm probably going to wait until then to tackle fixing this so that I can deal with any porting issues at the same time. Hopefully that still means soon though.

**Comment by stephenkraemer** [comment] 2020-02-11 07:20
That sounds great! Even with some minor bugs, this extension was essential for being able to switch to jupyterlab, so thank you very much!

**Comment by aquirdTurtle** [comment] 2020-03-19 00:29
This issue should be fixed as of version 2.2.0, just published. Let me know if there are any additional issues.

**Closed as completed by aquirdTurtle** 2020-03-19 00:29 UTC

**Comment by paulclou** [comment] 2020-06-17 16:47
> 
> 
> This issue should be fixed as of version 2.2.0, just published. Let me know if there are any additional issues.

Hi aquirdTurtle, is the behavior of uncollapsing cells when navigating with J/K intended? From what I see the settings for J/K is the same as ArrowUp/ArrowDown. Thanks.

**Comment by ghost** [comment] 2020-06-17 17:18
Is uncollapsing with J/K intended behavior? The settings for J/K seem to match the settings for ArrowUp and ArrowDown.

**Comment by barnettx** [comment] 2021-01-23 05:10
Rebuilding JupyterLab seemed to resolve the J/K unfolding issue.

Can be done in the Extensions menu after updating an extension which triggers a suggestion to rebuild
![image](https://user-images.githubusercontent.com/18087283/105569332-d1f83f80-5d7b-11eb-9930-ae636d7a0aaf.png)

Alternatively, can be done in the command line with `jupyter lab build`

I also restarted my JupyterLab server just to be sure. I'm using Google Cloud's Notebooks so JupyterLab is in a docker instance. It can be restarted with `sudo service jupyter restart` (https://cloud.google.com/ai-platform/notebooks/docs/troubleshooting#restart_the_jupyter_service)
